#!/usr/bin/env python3
"""Append reviewed university/classroom expressions to the Russian bundle.

The source lines are taken from the allowlisted Russian speaking-dialogue
corpus. Variant-heavy source lines are split into one concrete practice form;
the original sourceText and source hash remain attached for traceability.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "Sources" / "RussianCornerCore" / "Resources" / "long-term-sentences.json"


def card(
    *,
    identifier: str,
    prompt: str,
    cue: str,
    practice: str,
    stressed: str,
    theme: str,
    dialogue_act: str,
    register: str,
    speaker_role: str,
    address_form: str,
    reply: str,
    topic_id: str,
    source_path: str,
    source_text: str,
    provenance: str,
    quality_flags: list[str] | None = None,
) -> dict:
    return {
        "id": identifier,
        "promptZh": prompt,
        "cueRu": cue,
        "practiceRu": practice,
        "stressedForm": stressed,
        "speechText": practice,
        "theme": theme,
        "lexemeIDs": [],
        "sourcePath": source_path,
        "sourceText": source_text,
        "reviewStatus": "reviewed",
        "provenanceType": provenance,
        "qualityFlags": quality_flags or [],
        "dialogueAct": dialogue_act,
        "register": register,
        "speakerRole": speaker_role,
        "addressForm": address_form,
        "expectedReply": reply,
        "alternativeReplyIDs": [],
        "topicID": topic_id,
        "sourceHash": "",
    }


def build_cards() -> list[dict]:
    root = Path(json.loads(MANIFEST.read_text(encoding="utf-8"))["sourceRoot"])
    files = {
        "t21": "具体场景对话/Тема 21. Мой университет..md",
        "t22": "具体场景对话/Тема 22. Занятия. Экзамены..md",
        "t24": "具体场景对话/Тема 24. Международные контакты..md",
        "t06": "具体场景对话/тема 6 О работе. Об учёбе. 关于工作、学习.md",
    }
    raw: dict[str, tuple[str, str]] = {}
    for key, relative in files.items():
        path = root / relative
        data = path.read_bytes()
        raw[key] = (relative, hashlib.sha256(data).hexdigest())
    hashes_by_path = {relative: digest for relative, digest in raw.values()}

    rows = [
        card(
            identifier="longterm-campus-01",
            prompt="请带我参观一下你们学校。",
            cue="Как попросить преподавателя показать университет?",
            practice="Покажите нам ваш институт.",
            stressed="Покажи́те нам ваш институ́т.",
            theme="campus-teacher-greeting",
            dialogue_act="request",
            register="polite",
            speaker_role="学生对老师",
            address_form="вы",
            reply="Конечно, давайте начнём с главного корпуса.",
            topic_id="topic-21",
            source_path=raw["t21"][0],
            source_text="9. **Показывай (-те) нам твой (ваш) институт. 请带我们参观一下你的（你们的）学校。**",
            provenance="derived",
            quality_flags=["mixedAnnotation"],
        ),
        card(
            identifier="longterm-campus-02",
            prompt="我也更喜欢在阅览室学习。",
            cue="Как сказать, где вам удобнее заниматься?",
            practice="Я тоже предпочитаю работать в читальном зале.",
            stressed="Я то́же предпочита́ю рабо́тать в чита́льном за́ле.",
            theme="campus-teacher-greeting",
            dialogue_act="statement",
            register="neutral",
            speaker_role="学生与同学",
            address_form="notApplicable",
            reply="В читальном зале действительно удобно заниматься.",
            topic_id="topic-21",
            source_path=raw["t21"][0],
            source_text="15. **Я тоже предпочитаю работать в читальном зале. 我也喜欢在阅览室自习（学习）。**",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-03",
            prompt="请问，今天谁值日？",
            cue="Как уточнить организационный вопрос перед занятием?",
            practice="Скажите, кто сегодня дежурный?",
            stressed="Скажи́те, кто сего́дня дежу́рный?",
            theme="campus-teacher-greeting",
            dialogue_act="informationQuestion",
            register="polite",
            speaker_role="学生对老师",
            address_form="вы",
            reply="Сегодня дежурит Анна.",
            topic_id="topic-22",
            source_path=raw["t22"][0],
            source_text="3. Скажите, кто сегодня дежурный? 请问，今天谁值日？",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-04",
            prompt="请课后先别走。",
            cue="Как попросить студентов остаться после занятия?",
            practice="Не расходитесь, пожалуйста, после занятий.",
            stressed="Не расхо́дитесь, пожа́луйста, по́сле заня́тий.",
            theme="teacher-help-and-classroom",
            dialogue_act="request",
            register="polite",
            speaker_role="老师对学生",
            address_form="вы",
            reply="Хорошо, мы останемся после занятия.",
            topic_id="topic-22",
            source_path=raw["t22"][0],
            source_text="4. **Не расходитесь, пожалуйста, после занятий. 下课以后请不要走。**",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-05",
            prompt="好，我们开始上课吧。",
            cue="Как преподаватель начинает занятие?",
            practice="Ну, начнём наши занятия!",
            stressed="Ну, начнём на́ши заня́тия!",
            theme="teacher-help-and-classroom",
            dialogue_act="opening",
            register="neutral",
            speaker_role="老师对学生",
            address_form="вы",
            reply="Хорошо, начнём.",
            topic_id="topic-22",
            source_path=raw["t22"][0],
            source_text="5. Ну, начнём наши занятия! 好，我们现在开始上课。",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-06",
            prompt="我们先检查家庭作业。",
            cue="Что можно сказать перед проверкой домашней работы?",
            practice="Сначала проверим домашние задания.",
            stressed="Снача́ла прове́рим дома́шние зада́ния.",
            theme="teacher-help-and-classroom",
            dialogue_act="opening",
            register="neutral",
            speaker_role="老师对学生",
            address_form="вы",
            reply="Хорошо, я открою тетрадь.",
            topic_id="topic-22",
            source_path=raw["t22"][0],
            source_text="6. **Сначала проверим домашние задания. 先检查家庭作业。**",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-07",
            prompt="上一节课留了什么作业？",
            cue="Как спросить о домашнем задании?",
            practice="Что было задано на дом?",
            stressed="Что бы́ло за́дано на до́м?",
            theme="teacher-help-and-classroom",
            dialogue_act="informationQuestion",
            register="neutral",
            speaker_role="学生对同学或老师",
            address_form="вы",
            reply="Нужно было прочитать текст и ответить на вопросы.",
            topic_id="topic-22",
            source_path=raw["t22"][0],
            source_text="7. **Что было задано на дом? 上一节课留什么作业了？**",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-08",
            prompt="考试近在眼前了。",
            cue="Как сказать, что экзамен уже скоро?",
            practice="У нас экзамены уже на носу.",
            stressed="У нас экза́мены уже́ на носу́.",
            theme="classroom-answer",
            dialogue_act="statement",
            register="neutral",
            speaker_role="学生与同学",
            address_form="notApplicable",
            reply="Да, времени осталось совсем мало.",
            topic_id="topic-22",
            source_path=raw["t22"][0],
            source_text="9. **У нас экзамены уже на носу. 考试近在眼前啦。**",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-09",
            prompt="语法考试是口试还是笔试？",
            cue="Как уточнить формат экзамена?",
            practice="Какой будет экзамен по грамматике, устный или письменный?",
            stressed="Како́й бу́дет экза́мен по грамма́тике, у́стный и́ли пи́сьменный?",
            theme="classroom-question",
            dialogue_act="informationQuestion",
            register="polite",
            speaker_role="学生对老师",
            address_form="вы",
            reply="Сначала будет устная часть, а потом письменная.",
            topic_id="topic-22",
            source_path=raw["t22"][0],
            source_text="10. **Какой будет экзамен по грамматике, устный или письменный? 语法怎么考？是口试还是笔试？**",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-10",
            prompt="考试要考多长时间？",
            cue="Как спросить о продолжительности экзамена?",
            practice="Сколько времени даётся на экзамен?",
            stressed="Ско́лько вре́мени даётся на экза́мен?",
            theme="classroom-question",
            dialogue_act="informationQuestion",
            register="polite",
            speaker_role="学生对老师",
            address_form="вы",
            reply="На экзамен даётся девяносто минут.",
            topic_id="topic-22",
            source_path=raw["t22"][0],
            source_text="11. **Сколько времени даётся на экзамен? 考多长时间？**",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-11",
            prompt="请问，图书馆几点开放？",
            cue="Как уточнить часы работы университетской библиотеки?",
            practice="Скажите, пожалуйста, как работает библиотека?",
            stressed="Скажи́те, пожа́луйста, как рабо́тает библиоте́ка?",
            theme="campus-teacher-greeting",
            dialogue_act="informationQuestion",
            register="polite",
            speaker_role="学生对老师或工作人员",
            address_form="вы",
            reply="Библиотека работает до восьми вечера.",
            topic_id="topic-22",
            source_path=raw["t22"][0],
            source_text="18. **Скажи (-те), пожалуйста, как работает библиотека? 请问，图书馆几点工作？**",
            provenance="derived",
            quality_flags=["mixedAnnotation"],
        ),
        card(
            identifier="longterm-campus-12",
            prompt="哎呀，我把事情搞混了。",
            cue="Как исправиться, если вы перепутали ответ?",
            practice="Ой, я всё перепутал.",
            stressed="Ой, я всё перепу́тал.",
            theme="classroom-answer",
            dialogue_act="selfCorrection",
            register="neutral",
            speaker_role="男学生对老师",
            address_form="вы",
            reply="Ничего страшного, попробуйте ещё раз.",
            topic_id="topic-22",
            source_path=raw["t22"][0],
            source_text="19. **Ой, я всё перепутал (-ла). 哎呀，我搞混了。**",
            provenance="derived",
            quality_flags=["mixedAnnotation"],
        ),
        card(
            identifier="longterm-campus-13",
            prompt="您刚才说什么？请再重复一遍。",
            cue="Как попросить преподавателя повторить?",
            practice="Что вы сказали? Повторите, пожалуйста!",
            stressed="Что вы ска́зали? Повтори́те, пожа́луйста!",
            theme="classroom-question",
            dialogue_act="clarification",
            register="polite",
            speaker_role="学生对老师",
            address_form="вы",
            reply="Конечно, я повторю ещё раз.",
            topic_id="topic-22",
            source_path=raw["t06"][0],
            source_text="19. **Что вы сказали? Повторите, пожалуйста! 您说什么？请重复一下！**",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-14",
            prompt="我什么时候可以和导师见面？",
            cue="Как спросить о встрече с научным руководителем?",
            practice="Когда я могу встретиться с ним?",
            stressed="Когда́ я могу́ встре́титься с ним?",
            theme="teacher-help-and-classroom",
            dialogue_act="informationQuestion",
            register="polite",
            speaker_role="学生对外事老师",
            address_form="вы",
            reply="После занятия, если вам удобно.",
            topic_id="topic-24",
            source_path=raw["t24"][0],
            source_text="11. Когда я могу встретиться с ним (ней)? 我什么时候可以和他（她）见面？",
            provenance="derived",
            quality_flags=["mixedAnnotation"],
        ),
        card(
            identifier="longterm-campus-15",
            prompt="我们可以帮您什么忙？",
            cue="Как предложить помощь в учебной ситуации?",
            practice="Чем мы можем вам помочь?",
            stressed="Чем мы мо́жем вам помо́чь?",
            theme="teacher-help-and-classroom",
            dialogue_act="offerHelp",
            register="polite",
            speaker_role="老师对学生",
            address_form="вы",
            reply="Я хотел бы уточнить задание.",
            topic_id="topic-24",
            source_path=raw["t24"][0],
            source_text="13. **Чем мы можем вам помочь? 我们可以帮您什么忙？**",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-16",
            prompt="请允许我问一下，筹备委员会在哪里？",
            cue="Как вежливо спросить, где находится нужный кабинет?",
            practice="Разрешите узнать, где находится оргкомитет?",
            stressed="Разреши́те узна́ть, где находи́тся оргкомите́т?",
            theme="campus-teacher-greeting",
            dialogue_act="askLocation",
            register="polite",
            speaker_role="学生对工作人员",
            address_form="вы",
            reply="Оргкомитет находится на первом этаже.",
            topic_id="topic-24",
            source_path=raw["t24"][0],
            source_text="14. **Разрешите узнать, где находится** оргкомитет? **请允许我问一下**，筹备委员会在哪儿？",
            provenance="courseMaterial",
        ),
        card(
            identifier="longterm-campus-17",
            prompt="您能告诉我开幕式什么时候开始吗？",
            cue="Как уточнить время университетского мероприятия?",
            practice="Вы не скажете, когда состоится церемония открытия?",
            stressed="Вы не ска́жете, когда́ состо́ится церемо́ния откры́тия?",
            theme="classroom-question",
            dialogue_act="informationQuestion",
            register="polite",
            speaker_role="学生对工作人员",
            address_form="вы",
            reply="Церемония состоится в актовом зале.",
            topic_id="topic-24",
            source_path=raw["t24"][0],
            source_text="17. **Вы не скажете, когда** состоится церемония открытия? 您能否告诉我开幕式什么时候开始吗？",
            provenance="courseMaterial",
        ),
    ]
    for item in rows:
        item["sourceHash"] = hashes_by_path[item["sourcePath"]]
    return rows


def main() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    existing = {item["id"] for item in manifest["sentences"]}
    additions = [item for item in build_cards() if item["id"] not in existing]
    manifest["sentences"].extend(additions)
    MANIFEST.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(
        f"russian_campus_content=PASS added={len(additions)} "
        f"sentences={len(manifest['sentences'])}"
    )


if __name__ == "__main__":
    main()
